spring:
  datasource:
    url: jdbc:mysql://sh-cynosdbmysql-grp-38086q0k.sql.tencentcdb.com:26809/dni?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Fan20011001
  sql:
    init:
      mode: always
mybatis-plus:
  mapper-locations: classpath:repository/*.xml