server:
  port: 8099
spring:
  security:
    oauth2:
      client:
        registration:
          api-client:
            provider: spring
            client-id: dni
            client-secret: dni
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: api-client
          api-client-authorization:
            provider: spring
            client-id: dni
            client-secret: dni
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/authorized"
            scope: user.read
            client-name: api-client-authorization
        provider:
          spring:
            issuer-uri: http://localhost:9000